
from typing import Any
from fastapi import Response

options: dict[str, str | dict[str, Any]] = ...

class HeaderOptionError(Exception):
	def __init__(self, option: str, header_name: str) -> None: ...

def apply(response: Response) -> Response: ...
	
def strict_transport_security(response: Response) -> Response: ...
	
def content_security_policy(response: Response) -> Response: ...
	
def referrer_policy(response: Response) -> Response: ...
	
def cross_origin_embedder_policy(response: Response) -> Response: ...
	
def x_permitted_cross_domain_policies(response: Response) -> Response: ...

def cross_origin_opener_policy(response: Response) -> Response: ...

def x_frame_options(response: Response) -> Response: ...
	
def cross_origin_resource_policy(response: Response) -> Response: ...
	
def x_dns_prefetch_control(response: Response) -> Response: ...
	
def x_download_options(response: Response) -> Response: ...
	
def x_powered_by(response: Response) -> Response: ...

def x_xss_protection(response: Response) -> Response: ...

def x_content_type_options(response: Response) -> Response: ...

def origin_agent_cluster(response: Response) -> Response: ...
